# math
server "math.fent.uk" {
	listen on * port 80

	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}

	location * {
		block return 301 "https://$HTTP_HOST$REQUEST_URI"
	}
}

server "math.fent.uk" {
	listen on * tls port 443

	tls {
		certificate "/etc/ssl/math.fent.uk.fullchain.pem"
		key "/etc/ssl/private/math.fent.uk.key"
	}

	location "/static/*" {
		root "/math.fent.uk"
		no fastcgi
	}

	root "/cgi-bin/math.cgi"
	fastcgi socket "/run/slowcgi.sock"
}

